---
# handlers file for aws_utils

- name: "Replace IAM role"
  ec2_instance:
    region: "{{ ec2_instance.region }}"
    instance_role: "{{ aws_iam_role }}"
    instance_ids:
      - "{{ ec2_instance.id }}"
  when: aws_iam_role is defined
  tags: configuration