---
- name: loop over dns_record_list
  include_tasks: dnsrecord.yml
  loop: "{{ dns_record_list }}"
  loop_control:
    label: "{{ record.name }}"
    loop_var: record
  when:
    - dns_record_list is defined
  listen: "aws postactions"
  tags: configuration

- name: replace IAM role
  ansible.builtin.ec2_instance:
    region: "{{ ec2_instance.region }}"
    instance_role: "{{ aws_iam_role }}"
    instance_ids:
      - "{{ ec2_instance.id }}"
  when: aws_iam_role is defined
  listen: "aws postactions"
  tags: configuration
