---

- debug: 
    msg: "In flush_handlers recover mode"
  when: flush_handlers is defined
  tags: debug

- name: Flush handlers
  include_tasks:
    file: include_flush.yml
  register: flush_handlers
  when: discord_message_failure == false

- debug: var=flush_handlers
  tags: debug

- debug: var=ansible_failed_task verbosity=1
  tags: debug

- debug: var=ansible_failed_result verbosity=1
  tags: debug

- include_tasks: validate.yml
- include_tasks: _defaults.yml

- debug: var=discord_message_failure verbosity=1
  tags: debug

- name: send message
  community.general.discord: "{{_discord_message}}"