---

- debug: var=ansible_failed_task verbosity=1
  tags: debug

- debug: var=ansible_failed_result verbosity=1
  tags: debug

- include_tasks: validate.yml
- include_tasks: _defaults.yml

- debug: var=discord_message_failure verbosity=1
  tags: debug

- name: Flush handlers
  include_tasks:
    file: include_flush.yml
  when: discord_message_failure == false

- name: send message
  community.general.discord: "{{_discord_message}}"