---
# handlers file for ansible-telegraf

- name: include task restart telegraf
  ansible.builtin.include_tasks: restart_telegraf.yml
  listen: Restart Telegraf
  when: telegraf_service_start_and_enable