- name: Install alloy
  include_tasks:
    file: install.yml
    apply:
      tags: installation
  tags: installation

- name: Configure alloy
  include_tasks: 
    file: configure.yml
    apply:
      tags: configuration
  tags: configuration

- name: Manage alloy service
  include_tasks:
    file: service.yml
    apply:
      tags: configuration
  tags: configuration