---
# tasks file for consul

- name: consul_reverse_addr
  debug:
    msg: "{{ consul_reverse_addr }}"

- name: Installation
  ansible.builtin.include_tasks: 
    file: "installation.yml"
    apply:
      tags: installation
  when: consul_install
  tags: installation

- name: Configuration
  ansible.builtin.include_tasks: 
    file: "configuration.yml"
    apply:
      tags: configuration    
  when: consul_deploy
  tags: configuration
