---
# tasks file for consul

- name: consul_reverse_addr
  debug:
    msg: "{{ consul_reverse_addr }}"

- name: Dnsmasq role
  ansible.builtin.import_role:
    name: dnsmasq
  vars:
    dnsmasq_group: root
    dnsmasq_servers:
      - domain: consul
        nameserver: "127.0.0.1#{{ consul_ports_dns }}"
      - domain: "{{ consul_reverse_addr }}"
        nameserver: "127.0.0.1#{{ consul_ports_dns }}"
  when: not consul_server

- name: Installation
  ansible.builtin.include_tasks: 
    file: "installation.yml"
    apply:
      tags: installation
  when: consul_install
  tags: installation

- name: Configuration
  ansible.builtin.include_tasks: 
    file: "configuration.yml"
    apply:
      tags: configuration    
  when: consul_deploy
  tags: configuration
