---

- name: Data disk
  tags: configuration
  block:
    # Gather information about any volume that is attached
    - amazon.aws.ec2_vol_info:
        region: "{{ ec2_instance.region }}" 
        filters:
          "tag:b-HostRole": "{{ private_dns | default(ansible_hostname) }}-data"
          "availability-zone": "{{ ec2_instance.zone }}"
      register: vol_info
      until: vol_info.volumes | length == 0
            or ( vol_info.volumes | length == 1 
                  and (vol_info.volumes[0].status == "available" 
                        or (vol_info.volumes[0].status == "in-use" and vol_info.volumes[0].attachment_set[0].instance_id == ec2_instance.id) ) )
      retries: 30
      delay: 2
      ignore_errors: true

    - name: Fail if in use
      fail:
        msg: "volume {{ vol_info.volumes[0].id }} in use"
      when: vol_info.volumes | length == 1 and vol_info.volumes[0].status == "in-use"

    - debug: var=vol_info.volumes
      run_once: true
      tags: debug

    - set_fact: 
        ec2_instance: '{{ ec2_instance | combine({"data_volume_id": vol_info.volumes[0].id}) }}'
      when: vol_info.volumes | length == 1 and vol_info.volumes[0].status == "available"

    - set_fact: 
        ec2_instance: '{{ ec2_instance | combine({"data_volume_attached": vol_info.volumes[0].attachment_set[0].instance_id == ec2_instance.id }) }}'
      when: vol_info.volumes | length == 1 and vol_info.volumes[0].status == "in-use"

    - debug: var=ec2_instance
      tags: debug

    - name: Create new volume using SSD storage
      amazon.aws.ec2_vol:
        instance: "{{ ec2_instance.id }}"
        region: "{{ ec2_instance.region }}"
        volume_size: "{{ disk.size }}"
        volume_type: "{{ disk.type | default('gp3') }}"
        device_name: "{{ disk.name }}"
        delete_on_termination: "{{ private_dns is undefined or disk.delete_on_termination | default(false) }}"
        tags: {"b-HostRole": "{{ private_dns | default(ansible_hostname) }}-data", "Name":"{{ private_dns | default(ansible_hostname) }}-data", "b-app": "{{ disk.app | default(ansible_hostname) }}"}
        snapshot: "{{ data_snapshot|default(omit) }}"
        encrypted: "{{ disk.kms_key_id is defined }}"
        kms_key_id: "{{ disk.kms_key_id }}"
      register: ec2_vol
      when: ec2_instance.data_volume_id is undefined and not (ec2_instance.data_volume_attached | default(false))

    - name: Attach an existing volume to instance.
      amazon.aws.ec2_vol:
        instance: "{{ ec2_instance.id }}"
        region: "{{ ec2_instance.region }}"
        id: "{{ ec2_instance.data_volume_id }}"
        device_name: "{{ disk.name }}"
      register: ec2_vol
      when: ec2_instance.data_volume_id is defined and not (ec2_instance.data_volume_attached | default(false))

    - debug: var=ec2_vol
      tags: debug

    - name: Mount disk
      import_role:
        name: mount_disk
      when: disk is defined