---

- name: Check if hashicorp repo exists
  stat:
    path: /etc/yum.repos.d/hashicorp.repo
  register: hashicorp_repo_result

- name: Add HashiCorp repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: HashiCorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/AmazonLinux/latest/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg
  tags: installation
  when: not hashicorp_repo_result.stat.exists

- name: Install consul
  ansible.builtin.package:
    name: consul
    state: present
  when:
    - consul_install_package
