---

- name: Mount disk
  when: disk_configure
  tags: configuration
  block:

    - debug: var=disk
      tags: debug
    
    - name: "Ensure the mount directory exists"
      file:
        path: '{{ disk.mount }}'
        owner: '{{ disk.user }}'
        group: '{{ disk.group }}'
        state: directory

    - name: Create filesystem
      community.general.filesystem:
        fstype: "{{ disk.fstype }}"
        dev: "{{ disk.name }}"
      register: filesystem

    - name: "Get symlink target"
      command: readlink -f {{ disk.name }}
      register: readlink_out

    - debug: var=readlink_out
      tags: debug

    - name: "Get UUID for partition"
      command: blkid -s UUID -o value {{ readlink_out.stdout }}
      register: disk_blkid
      changed_when: False

    - name: "Mount additional disk"
      mount:
        name: '{{ disk.mount }}'
        fstype: '{{ disk.fstype }}'
        opts: '{{ disk.mount_options|d(omit) }}'
        passno: '0'
        src: 'UUID={{ disk_blkid.stdout }}'
        state: '{{ disk.mount_state|d("mounted") }}'

    - name: "Ensure the permissions are set correctly"
      file:
        path: '{{ disk.mount }}'
        owner: '{{ disk.user }}'
        group: '{{ disk.group }}'
        state: directory