---
# defaults file for consul-template
consul_template_user: consult
consul_template_group: consult
consul_template_version: "latest"
consul_template_os_family: "linux"
consul_template_cpu_arch: "arm64"
consul_template_archive_file: "consul_template.zip"
consul_template_staging_area: "/tmp"
consul_template_binary: consul-template
consul_template_home: /opt/consul-template
consul_template_use_config_dir: false
consul_template_config_file_template: consul-template.cfg.j2
consul_template_config_file: consul-template.cfg
consul_template_log_file: /var/log/consul-template
consul_template_log_level: "INFO"
consul_template_consul_server: "127.0.0.1"
consul_template_consul_port: "8500"
consul_template_use_systemd: true
consul_template_service_start_and_enable: "{{ 'all' in ansible_run_tags or 'configuration' in ansible_run_tags }}"
consul_template_template_files: [] # see readme for usage
consul_template_templates: [] # - {name: "template.ctmpl", dest: "/path/on/disk/where/template/will/render", cmd: "optional command to run when the template is updated", perms: 0600, backup: false}
consul_template_template_templates: [] # - {name: "template.ctmpl.j2", dest: "/path/on/disk/where/template/will/render", cmd: "optional command to run when the template is updated", perms: 0600, backup: true}
