---
- debug: var=dns_record_list
  tags: debug

- name: Extend OS family
  ansible.builtin.include_role:
    name: aws_utils
    tasks_from: extend_os_family
    apply:
      tags: always
  tags: always
  when: not skip_extend_os_family

- name: Extend OS sub family
  ansible.builtin.include_role:
    name: aws_utils
    tasks_from: extend_os_sub_family
    apply:
      tags: always
  tags: always

- name: Collect instance info
  ansible.builtin.import_role:
    name: aws_utils
    tasks_from: collect_instance_info_speedy
  
- name: Set facts based on tag mappings
  set_fact:
    "{{ item.value }}": "{{ ec2_instance.tags[item.key] }}"
  when:
    - ec2_instance.tags[item.key] is defined
    - tags_facts is defined
  with_dict: "{{ tags_facts | default({}) }}"
  tags: 
    - installation
    - configuration

- name: Process datadisk
  import_role: 
    name: aws_utils
    tasks_from: datadisk
  when: disk is defined and disk.enable | default (true)

- set_fact:
    notify_aws_postactions: true
  tags: configuration