---
# tasks file for dnsmasq

- name: "Install"
  include_tasks: "install.yml"
  args:
    apply:
      tasks: installation
  when: dnsmasq_install
  tasks: installation

- name: "Deploy"
  include_tasks: "deploy.yml"
  args:
    apply:
      tasks: configuration
  when: dnsmasq_deploy
  tasks: configuration
