---
# tasks file for loki
- name: Include OS specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Deploy Loki service
  ansible.builtin.include_tasks:
    file: "deploy.yml"
    apply:
      tags: loki_deploy
  tags: loki_deploy

