---
- name: Java installation and setup
  tags: installation
  block:

    - name: Install Java 21
      ansible.builtin.dnf:
        name: java-21-amazon-corretto.aarch64
        state: present

    - name: Verify Java installation
      ansible.builtin.command:
        cmd: java --version
      register: java_version

    - name: Display Java version
      ansible.builtin.debug:
        var: java_version.stdout_lines
      tags: debug

    - name: Java home
      ansible.builtin.include_tasks: javahome.yml