---

  - debug:
      msg: "discord_webhook:'{{  discord_webhook }}'"
    tags: debug
    when: discord_webhook is defined

  - debug:
      msg: "discord_message_webhook_id:'{{  discord_message_webhook_id | default('') }}' , discord_message_webhook_token:'{{ discord_message_webhook_token | default('') }}'"
    tags: debug
    when: discord_message_webhook_url is defined

  - debug:
      msg: "discord_message_webhook_url:'{{  discord_message_webhook_url }}'"
    tags: debug
    when: discord_message_webhook_url is defined

  - name: Validate webhook_id
    fail:
      msg: "Either 'discord_message.webhook_id' or 'discord_message_webhook_id' is mandatory and cannot be empty."
    when: >
      (discord_message_webhook_id is not defined or discord_message_webhook_id | length == 0) and
      (discord_message.webhook_id is not defined or discord_message.webhook_id | length == 0)

  - name: Validate webhook_token
    fail:
      msg: "Either 'discord_message.webhook_token' or 'discord_message_webhook_token' is mandatory and cannot be empty."
    when: >
      (discord_message_webhook_token is not defined or discord_message_webhook_token | length == 0) and
      (discord_message.webhook_token is not defined or discord_message.webhook_token | length == 0)