---

- name: "Create systemd service for shrinking logs"
  ansible.builtin.template:
    src: shrink-logs.service.j2
    dest: /etc/systemd/system/shrink-logs.service
    mode: '0644'

- name: "Reload systemd"
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "Unmask shrinklogs service"
  ansible.builtin.systemd_service:
    name: shrink-logs
    enabled: true
    masked: false

- name: "Create systemd timer for shrinking logs"
  ansible.builtin.template:
    src: shrink-logs.timer.j2
    dest: /etc/systemd/system/shrink-logs.timer
    mode: '0644'

- name: "Enable and start shrinklogs timer"
  ansible.builtin.systemd_service:
    name: shrink-logs.timer
    enabled: true
    masked: false
    state: started