---
# tasks file for dnsmasq

- name: "Install"
  include_tasks: "install.yml"
  args:
    apply:
      tags: installation
  when: dnsmasq_install
  tags: installation

- name: "Deploy"
  include_tasks: "deploy.yml"
  args:
    apply:
      tags: configuration
  when: dnsmasq_deploy
  tags: configuration
