- name: disable hugepage
  command: echo never > /sys/kernel/mm/transparent_hugepage/enabled

- name: disable hugepage defrag
  command: echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: add a vm.swappiness setting at the end of the sysctl.conf
  sysctl: name=vm.swappiness value=10 state=present reload=yes

- include_role:
    name: sysctl
  vars:
    sysctl_items:
      - name: net.core.somaxconn
        value: 10240
      - name: net.ipv4.tcp_max_syn_backlog
        value: 10240

- name: configure system settings, file descriptors and number of threads
  pam_limits:
    domain: "{{ulimit.user}}"
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: '-', limit_item: 'nofile', value: 65536 }
    - { limit_type: '-', limit_item: 'nproc', value: 65536 }
    - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
    - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }

- name: reload settings from all system configuration files
  shell: sysctl --system