---
- name: Kafka configure
  tags: always
  block:
    - name: Configure system settings, file descriptors and number of threads
      pam_limits:
        domain: "{{ulimit.user}}"
        limit_type: "{{item.limit_type}}"
        limit_item: "{{item.limit_item}}"
        value: "{{item.value}}"
      with_items:
        - { limit_type: '-', limit_item: 'nofile', value: 65536 }
        - { limit_type: '-', limit_item: 'nproc', value: 65536 }
        - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
        - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }
    
    - name: Reload settings from all system configuration files
      ansible.builtin.command:
        cmd: sysctl --system
    
    - name: Set sysctl parameters
      ansible.builtin.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      loop:
        - name: net.core.somaxconn
          value: 10240
        - name: net.ipv4.tcp_max_syn_backlog
          value: 10240
