---

- name: import Hashicorp rpm gpg key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.releases.hashicorp.com/gpg

- name: Add repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: Hashicorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/AmazonLinux/latest/$basearch/stable
  become: true

- name: install Boundary
  yum:
    name: "boundary-{{ boundary_version }}"
  become: true
  register: boundary_package
  notify:
    - restart boundary-controller daemon
    - restart boundary-worker daemon
